import type { SkillGroup } from "@/types/content";

export const skillGroups: SkillGroup[] = [
  {
    id: "languages",
    title: { pt: "Linguagens", en: "Languages" },
    items: ["TypeScript", "JavaScript", "Java", "Python", "PHP", "SQL", "HTML5", "CSS3", "C#"],
  },
  {
    id: "frontend",
    title: { pt: "Frontend", en: "Frontend" },
    items: [
      "React",
      "Next.js",
      "Angular",
      "Vue.js",
      "TanStack Query",
      "Zustand",
      "Tailwind CSS",
      "shadcn/ui",
      "SCSS",
      "Bootstrap",
      "Vite",
    ],
  },
  {
    id: "mobile",
    title: { pt: "Mobile", en: "Mobile" },
    items: ["React Native", "Expo", "EAS Build", "Flutter"],
  },
  {
    id: "backend",
    title: { pt: "Backend", en: "Backend" },
    items: [
      "Node.js",
      "NestJS",
      "Express",
      "FastAPI",
      "Laravel",
      "Java (Servlets/JSP)",
      { pt: "APIs REST", en: "REST APIs" },
      "OAuth2",
      "OIDC",
      "JWT",
    ],
  },
  {
    id: "databases",
    title: { pt: "Bancos de dados e ORMs", en: "Databases and ORMs" },
    items: [
      "PostgreSQL",
      "MongoDB",
      "SQL Server",
      "Oracle",
      "MySQL",
      "Prisma",
      "Mongoose",
      "Hibernate",
      "Eloquent",
    ],
  },
  {
    id: "cloud-devops",
    title: { pt: "Cloud e DevOps", en: "Cloud and DevOps" },
    items: [
      "Google Cloud (Cloud Run, Cloud SQL, Cloud Build)",
      "AWS",
      "Vercel",
      "Docker",
      "GitHub Actions",
      "Jenkins",
      "CI/CD",
    ],
  },
  {
    id: "applied-ai",
    title: { pt: "IA aplicada", en: "Applied AI" },
    items: [
      "LLMs (Gemini)",
      { pt: "Agentes com tool calling", en: "Tool-calling agents" },
      { pt: "Ingestão de base de conhecimento", en: "Knowledge-base ingestion" },
      { pt: "Cache de contexto", en: "Context caching" },
    ],
  },
  {
    id: "testing",
    title: { pt: "Testes e qualidade", en: "Testing and quality" },
    items: [
      "Jest",
      "Vitest",
      "Testing Library",
      "Cypress",
      "pytest",
      "JUnit",
      "MSW",
      "Supertest",
      "Postman",
    ],
  },
  {
    id: "practices",
    title: { pt: "Práticas", en: "Practices" },
    items: [
      "Clean Architecture",
      "Code review",
      "ADRs",
      "Git/GitFlow",
      { pt: "Metodologias ágeis", en: "Agile" },
      "Core Web Vitals",
      "SEO",
      { pt: "Acessibilidade", en: "Accessibility" },
      "Figma",
    ],
  },
];
